name = "Anarchy Pack"
author = "Maciej @yungbruh1337 Błędkowski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "200c35e58c0d7de6bbe49badb3891167b21128d0d153c5e97b734e4bb068f046"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
