name = "Anarchy Pack"
author = "Maciej @yungbruh1337 Błędkowski"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "284cafeb0fdc6f831e850f094f42c57f97469d84a5e01e0c4ad54d2b29dab3f4"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
