name = "Anarchy Pack"
author = "Maciej @yungbruh1337 Błędkowski"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80986d8e49f1d2066263c6039f56ef3b7711bdcee6656e9e77a0ef51c751c937"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
